In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter('ignore')
from sklearn.ensemble import GradientBoostingClassifier
from string import punctuation

In [2]:
deliveries = pd.read_csv('C:/Users/Dell/Data science/ipldata/deliveries.csv')
matches = pd.read_csv('C:/Users/Dell/Data science/ipldata/matches.csv')

In [3]:
CSK = ['MS Dhoni', 'KM Asif', 'SW Billings', 'C Bishnoi', 'DJ Bravo', 'DL Chahar', 'F du Plessis', 'RD Gaikwad', 'Harbhajan Singh', 'Imran Tahir', 'RA Jadeja', 'KM Jadhav', 'N Jagadeesan', 'Monu Kumar', 'L Ngidi', 'SK Raina', 'AT Rayudu', 'MJ Santner', 'KV Sharma', 'MM Sharma', 'DR Shorey', 'SN Thakur', 'M Vijay', 'SR Watson', 'DJ Willey']

RCB = ['V Kohli', 'AD Nath', 'MM Ali', 'YS Chahal', 'NM Coulter-Nile', 'C de Grandhomme', 'AB de Villiers', 'S Dube', 'Gurkeerat Singh', 'SO Hetmyer', 'Himmat Singh', 'K Khejroliya', 'H Klaasen', 'Milind Kumar', 'Mohammed Siraj', 'P Negi', 'D Padikkal', 'PA Patel', 'P Ray Barman', 'NA Saini', 'TG Southee', 'MP Stoinis', 'Washington Sundar', 'UT Yadav']

KKR = ['KD Karthik', 'CR Brathwaite', 'PP Chawla', 'JL Denly', 'LH Ferguson', 'HF Gurney', 'Kuldeep Yadav', 'CA Lynn', 'SS Mundhe', 'KL Nagarkoti', 'NS Naik', 'SP Narine', 'A Nortje', 'M Prasidh Krishna', 'Y Prithvi Raj', 'N Rana', 'AD Russell', 'Shivam Mavi', 'Shubman Gill', 'RK Singh', 'RV Uthappa']

SRH = ['DA Warner', 'Abhishek Sharma', 'KK Ahmed', 'JM Bairstow', 'Basil Thampi', 'RK Bhui', 'SP Goswami', 'MJ Guptill', 'DJ Hooda', 'S Kaul', 'B Kumar', 'Mohammad Nabi', 'S Nadeem', 'T Natarajan', 'MK Pandey', 'YK Pathan', 'Rashid Khan', 'WP Saha', 'Sandeep Sharma', 'V Shankar', 'Shakib Al Hasan', 'B Stanlake', 'KS Williamson']

MI = ['RG Sharma', 'Anmolpreet Singh', 'JP Behrendorff', 'JJ Bumrah', 'RD Chahar', 'BCJ Cutting', 'Q de Kock', 'Ishan Kishan', 'PP Jaiswal', 'SD Lad', 'E Lewis', 'MJ McClenaghan', 'SL Malinga', 'M Markande', 'AF Milne', 'HH Pandya', 'KH Pandya', 'KA Pollard', 'Rasikh Salam', 'AS Roy', 'BB Sran', 'AP Tare', 'SA Yadav', 'Yuvraj Singh']

DC = ['Avesh Khan', 'B Ayyappa', 'AK Bains', 'TA Boult', 'S Dhawan', 'CA Ingram', 'SS Iyer', 'S Lamichhane', 'Manjot Kalra', 'A Mishra', 'CH Morris', 'C Munro', 'RR Pant', 'AR Patel', 'HV Patel', 'KMA Paul', 'K Rabada', 'SE Rutherford', 'Jalaj S Saxena', 'I Sharma', 'PP Shaw', 'NB Singh', 'R Tewatia', 'GH Vihari', 'J Yadav']

RR = ['SPD Smith', 'VR Aaron', 'JC Archer', 'STR Binny', 'AV Birla', 'JC Buttler', 'P Chopra', 'S Gopal', 'K Gowtham', 'DS Kulkarni', 'LS Livingstone', 'MK Lomror', 'S Midhun', 'R Parag', 'AM Rahane', 'SS Ranjane', 'SV Samson', 'Shashank Singh', 'IS Sodhi', 'BA Stokes', 'O Thomas', 'RA Tripathi', 'AJ Turner', 'JD Unadkat', 'M Vohra']

KXIP = ['MA Agarwal', 'Arshdeep Singh', 'M Ashwin', 'R Ashwin', 'AC Ayachi', 'SM Curran', 'CH Gayle', 'Harpreet Brar', 'MC Henriques', 'SN Khan', 'Mandeep Singh', 'DA Miller', 'Mohammed Shami', 'Mujeeb Ur Rahman', 'KK Nair', 'DG Nalkande', 'N Pooran', 'KL Rahul', 'AS Rajpoot', 'P Simran Singh', 'AJ Tye', 'CV Varun', 'GC Viljoen']

In [4]:
def replace(x) :
    return ''.join([i for i in x if i not in punctuation])

In [5]:
matches['venue'] = matches['venue'].apply(replace)
matches['venue'] = matches['venue'].apply(lambda x: x.replace('Punjab Cricket Association IS Bindra Stadium Mohali','Punjab Cricket Association Stadium Mohali'))
venues= list(matches.venue.value_counts().index)
venues

['M Chinnaswamy Stadium',
 'Eden Gardens',
 'Feroz Shah Kotla',
 'Wankhede Stadium',
 'Rajiv Gandhi International Stadium Uppal',
 'MA Chidambaram Stadium Chepauk',
 'Punjab Cricket Association Stadium Mohali',
 'Sawai Mansingh Stadium',
 'Maharashtra Cricket Association Stadium',
 'Dr DY Patil Sports Academy',
 'Subrata Roy Sahara Stadium',
 'Kingsmead',
 'SuperSport Park',
 'Sardar Patel Stadium Motera',
 'Dr YS Rajasekhara Reddy ACAVDCA Cricket Stadium',
 'Brabourne Stadium',
 'Saurashtra Cricket Association Stadium',
 'Holkar Cricket Stadium',
 'Himachal Pradesh Cricket Association Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'St Georges Park',
 'Sheikh Zayed Stadium',
 'Barabati Stadium',
 'Dubai International Cricket Stadium',
 'JSCA International Stadium Complex',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Nehru Stadium',
 'Green Park',
 'Buffalo Park',
 'Vidarbha Cricket Association Stadium Jamtha',
 'De Beers Diamond Oval',
 'OUTsur

In [6]:
def balls(cols) :
    x = cols[0]
    y = cols[1]
    if x > 0 or y > 0 :
        return 0
    else :
        return 1
def out_bowler(x) :
    if x in ('caught','bowled','lbw','stumped','caught and bowled','hit wicket') :
        return 1
    else :
        return 0
def team(x) :
    if x in CSK :
        return 'CSK'
    elif x in RCB :
        return 'RCB'
    elif x in KKR :
        return 'KKR'
    elif x in SRH :
        return 'SRH'
    elif x in MI :
        return 'MI'
    elif x in DC :
        return 'DC'
    elif x in RR :
        return 'RR'
    elif x in KXIP :
        return 'KXIP'
    else :
        return 'None'
    
def is_played(cols):
    x = cols[0]
    y = cols[1]
    if x >= 20:
        return 1
    elif  x < 20 and x >= 10 and y==0 :
        return 1
    else :
        return 0
    
def fillna(cols) :
    x1 = cols[0]
    x2 = cols[1]
    x3 = cols[2]
    return (x1+x2+x3)/3

def fillna2(cols) :
    x1 = cols[0]
    x2 = cols[1]
    return (x1+x2)/2

In [7]:
total_df = pd.merge(left=deliveries,right=matches,left_on='match_id',right_on='id')
total_df['balls'] = total_df[['wide_runs','noball_runs']].apply(balls,axis=1)
total_df['out_bowler'] = total_df['dismissal_kind'].apply(out_bowler)
total_df.drop(labels=['wide_runs','bye_runs','legbye_runs','noball_runs','penalty_runs','id','player_dismissed','dismissal_kind','extra_runs','total_runs'],axis=1,inplace=True)
total_df['Own_Team'] = total_df['batsman'].apply(team)
total_df['Opp_Team'] = total_df['bowler'].apply(team)
total_df = total_df.groupby(by=['match_id','batsman','bowler','venue','Own_Team','Opp_Team'],as_index=False).sum()[['match_id','batsman','bowler','batsman_runs','venue','balls','out_bowler','Own_Team','Opp_Team']]
total_df = total_df[(total_df['Own_Team']!='None') & (total_df['Opp_Team']!='None') & (total_df['Opp_Team']!= total_df['Own_Team'])]

In [8]:
total_df.head()

match_id      batsman       bowler  batsman_runs  \
1          1  BCJ Cutting    SR Watson            15   
4          1     CH Gayle      B Kumar            10   
5          1     CH Gayle  BCJ Cutting             4   
6          1     CH Gayle     DJ Hooda             6   
10         1     DJ Hooda    SR Watson             1   

                                       venue  balls  out_bowler Own_Team  \
1   Rajiv Gandhi International Stadium Uppal      5           0       MI   
4   Rajiv Gandhi International Stadium Uppal      7           0     KXIP   
5   Rajiv Gandhi International Stadium Uppal      6           0     KXIP   
6   Rajiv Gandhi International Stadium Uppal      3           1     KXIP   
10  Rajiv Gandhi International Stadium Uppal      1           0      SRH   

   Opp_Team  
1       CSK  
4       SRH  
5        MI  
6       SRH  
10      CSK

In [9]:
batting_score = total_df.groupby(by=['match_id','batsman','Own_Team','Opp_Team','venue'],as_index=False).sum()[['match_id','batsman','Own_Team','Opp_Team','venue','batsman_runs','out_bowler']]

In [10]:
batting_score.head()

match_id      batsman Own_Team Opp_Team  \
0         1  BCJ Cutting       MI      CSK   
1         1     CH Gayle     KXIP       MI   
2         1     CH Gayle     KXIP      SRH   
3         1     DJ Hooda      SRH      CSK   
4         1     DJ Hooda      SRH      RCB   

                                      venue  batsman_runs  out_bowler  
0  Rajiv Gandhi International Stadium Uppal            15           0  
1  Rajiv Gandhi International Stadium Uppal             4           0  
2  Rajiv Gandhi International Stadium Uppal            16           1  
3  Rajiv Gandhi International Stadium Uppal             1           0  
4  Rajiv Gandhi International Stadium Uppal             2           0

In [23]:
teams = ['CSK','RCB','KKR','SRH','MI','DC','RR','KXIP']

In [132]:
a = np.array([1])
handling_features(a)

array([ 1., nan, nan])

In [131]:
def handling_features(a) :
    if len(a) == 3 :
        return a
    elif len(a) == 2 :
        a = np.append(a,np.NaN)
        return a
    elif len(a) == 1 :
        a = np.append(a,np.NaN)
        a = np.append(a,np.NaN)
        return a

In [139]:
def fill_method(bat5) :
    bat5['pre_opp1'].fillna(value=bat5[['pre1','pre2','pre3']].apply(fillna,axis=1),inplace=True)
    bat5['pre_opp2'].fillna(value=bat5['pre_opp1'],inplace=True)
    bat5['pre_opp3'].fillna(value=bat5[['pre_opp1','pre_opp2']].apply(fillna2,axis=1),inplace=True)

    bat5['pre_venue1'].fillna(value=bat5[['pre1','pre2','pre3']].apply(fillna,axis=1),inplace=True)
    bat5['pre_venue2'].fillna(value=bat5['pre_venue1'],inplace=True)
    bat5['pre_venue3'].fillna(value=bat5[['pre_venue1','pre_venue2']].apply(fillna2,axis=1),inplace=True)

    bat5['bowl_opp1'].fillna(value=bat5[['bowl_pre1','bowl_pre2','bowl_pre3']].apply(fillna,axis=1),inplace=True)
    bat5['bowl_opp2'].fillna(value=bat5['bowl_opp1'],inplace=True)
    bat5['bowl_opp3'].fillna(value=bat5[['bowl_opp1','bowl_opp2']].apply(fillna2,axis=1),inplace=True)

    bat5['venue_opp1'].fillna(value=bat5[['bowl_pre1','bowl_pre2','bowl_pre3']].apply(fillna,axis=1),inplace=True)
    bat5['venue_opp2'].fillna(value=bat5['venue_opp1'],inplace=True)
    bat5['venue_opp3'].fillna(value=bat5[['venue_opp1','venue_opp2']].apply(fillna2,axis=1),inplace=True)

def batting_per(batting_score,player,own_team,opp_team,match_venue,teams,venues) :

    df = batting_score[batting_score['batsman']==player]
    df = df.sort_values(by='match_id')
    df['pre1'] = df['batsman_runs'].shift(1)
    df['pre2'] = df['batsman_runs'].shift(2)
    df['pre3'] = df['batsman_runs'].shift(3)
    df.dropna(inplace=True)
    
    opp_df = pd.DataFrame()
    for i in [i for i in teams if i not in own_team] :
        opp = batting_score[(batting_score['batsman']==player) & (batting_score['Opp_Team']==i)]
        opp = opp.sort_values(by='match_id')
        opp['pre_opp1'] = opp['batsman_runs'].shift(1)
        opp['pre_opp2'] = opp['batsman_runs'].shift(2)
        opp['pre_opp3'] = opp['batsman_runs'].shift(3)
        opp_df = opp_df.append(opp)
    opp_df = opp_df[['match_id','batsman','Opp_Team','venue','pre_opp1','pre_opp2','pre_opp3']]
    bat1 = pd.merge(df,opp_df,left_on=['match_id','batsman','Opp_Team','venue'],right_on=['match_id','batsman','Opp_Team','venue'],how='left')
    
    venue_df = pd.DataFrame()
    for j in venues :
        ven = batting_score[(batting_score['batsman']==player) & (batting_score['venue']==j)]
        ven = ven.sort_values(by='match_id')
        ven['pre_venue1'] = ven['batsman_runs'].shift(1)
        ven['pre_venue2'] = ven['batsman_runs'].shift(2)
        ven['pre_venue3'] = ven['batsman_runs'].shift(3)
        venue_df = venue_df.append(ven)
    venue_df = venue_df[['match_id','batsman','Opp_Team','venue','pre_venue1','pre_venue2','pre_venue3']]
    bat2 = pd.merge(bat1,venue_df,left_on=['match_id','batsman','Opp_Team','venue'],right_on=['match_id','batsman','Opp_Team','venue'],how='left')
    
    bowl_opp_df = pd.DataFrame()
    for i in [i for i in teams if i not in own_team] :
        bowl_opp = batting_score[(batting_score['Own_Team']==own_team) & (batting_score['Opp_Team']==i)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
        bowl_opp = bowl_opp.sort_values(by='match_id')
        bowl_opp['avg'] = bowl_opp['batsman_runs'] / bowl_opp['out_bowler'].apply(lambda x: 1 if x==0 else x)
        bowl_opp['bowl_opp1'] = bowl_opp['avg'].shift(1)
        bowl_opp['bowl_opp2'] = bowl_opp['avg'].shift(2)
        bowl_opp['bowl_opp3'] = bowl_opp['avg'].shift(3)
        bowl_opp_df = bowl_opp_df.append(bowl_opp)
    bat3 = pd.merge(bat2,bowl_opp_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
    bat3 = bat3[['match_id', 'batsman', 'Own_Team', 'Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 'pre1', 'pre2', 'pre3', 'pre_opp1',
           'pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 'pre_venue3','bowl_opp1', 'bowl_opp2','bowl_opp3']]
    
    bowl_df = pd.DataFrame()
    for i in [i for i in teams if i not in own_team] :
        bowl = batting_score[(batting_score['Opp_Team']==i)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
        bowl = bowl.sort_values(by='match_id')
        bowl['avg'] = bowl['batsman_runs'] / bowl['out_bowler'].apply(lambda x: 1 if x==0 else x)
        bowl['bowl_pre1'] = bowl['avg'].shift(1)
        bowl['bowl_pre2'] = bowl['avg'].shift(2)
        bowl['bowl_pre3'] = bowl['avg'].shift(3)
        bowl_df = bowl_df.append(bowl)
        bowl_df.dropna(inplace=True)
    bat4 = pd.merge(bat3,bowl_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
    bat4 = bat4[['match_id', 'batsman', 'Own_Team', 'Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 'pre1', 'pre2', 'pre3', 'pre_opp1',
           'pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 'pre_venue3','bowl_pre1', 'bowl_pre2', 'bowl_pre3','bowl_opp1', 'bowl_opp2','bowl_opp3']]
    
    bowl_venue_df = pd.DataFrame()
    for i in [i for i in teams if i not in own_team] :
        for j in venues :
            bowl_venue = batting_score[(batting_score['Opp_Team']==i) & (batting_score['venue']==j)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
            bowl_venue = bowl_venue.sort_values(by='match_id')
            bowl_venue['avg'] = bowl_venue['batsman_runs'] / bowl_venue['out_bowler'].apply(lambda x: 1 if x==0 else x)
            bowl_venue['venue_opp1'] = bowl_venue['avg'].shift(1)
            bowl_venue['venue_opp2'] = bowl_venue['avg'].shift(2)
            bowl_venue['venue_opp3'] = bowl_venue['avg'].shift(3)
            bowl_venue_df = bowl_venue_df.append(bowl_venue)
    bat5 = pd.merge(bat4,bowl_venue_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
    bat5 = bat5[['Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 
                 'pre1', 'pre2', 'pre3', 'pre_opp1','pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 
                 'pre_venue3','bowl_pre1', 'bowl_pre2', 'bowl_pre3','bowl_opp1', 'bowl_opp2','bowl_opp3',
                 'venue_opp1','venue_opp2', 'venue_opp3']]
    
    fill_method(bat5)
    
    bat_dummies = pd.get_dummies(bat5,columns=['Opp_Team','venue'])
    bat_dummies.dropna(inplace=True)
    
    if bat_dummies.shape[0] >= 25 :
    
        bat_dummies['is_played']=bat_dummies[['batsman_runs_x','out_bowler_x']].apply(is_played,axis=1)
        X_train = bat_dummies.iloc[:-5,2:-1]
        y_train = bat_dummies.iloc[:-5,-1]
        X_test = bat_dummies.iloc[-5:,2:-1]
        y_test = bat_dummies.iloc[-5:,-1]
        X_val = np.zeros(X_test.shape[1])
        a1 = batting_score[(batting_score['batsman']==player)].sort_values(by='match_id').tail(3)['batsman_runs'].values
        X_val[0:3] = handling_features(a1)
        
        a2 = batting_score[(batting_score['batsman']==player) & 
                                   (batting_score['Opp_Team']==opp_team)].sort_values(by='match_id').tail(3)['batsman_runs'].values
        X_val[3:6] = handling_features(a2)
        a3 = batting_score[(batting_score['batsman']==player) & 
                                   (batting_score['venue']==match_venue)].sort_values(by='match_id').tail(3)['batsman_runs'].values
        X_val[6:9] = handling_features(a3)
        b1 = batting_score[(batting_score['Opp_Team']==opp_team)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']].sort_values(by='match_id').tail(3)[['batsman_runs','out_bowler']]
        b1['avg'] = b1['batsman_runs'] / b1['out_bowler'].apply(lambda x: 1 if x==0 else x)
        X_val[9:12] = handling_features(b1['avg'].values)
        
        b2 = batting_score[(batting_score['Own_Team']==own_team) & (batting_score['Opp_Team']==opp_team)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']].sort_values(by='match_id').tail(3)[['batsman_runs','out_bowler']]
        b2['avg'] = b2['batsman_runs'] / b2['out_bowler'].apply(lambda x: 1 if x==0 else x)
        X_val[12:15] = handling_features(b2['avg'].values)
        
        b3 = batting_score[(batting_score['Opp_Team']==opp_team) & (batting_score['venue']==match_venue)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']].sort_values(by='match_id').tail(3)[['batsman_runs','out_bowler']]
        b3['avg'] = b3['batsman_runs'] / b3['out_bowler'].apply(lambda x: 1 if x==0 else x)
        X_val[15:18] = handling_features(b3['avg'].values)
        
        opposition = 'Opp_Team_'+ opp_team
        for i in range(0,len(X_train.columns)) :
            if opposition in X_train.columns[i] :
                opp_index = i
                X_val[opp_index] = 1
        
        match_venue = 'venue_'+ match_venue
        for i in range(0,len(X_train.columns)) :
            if match_venue in X_train.columns[i] :
                venue_index = i
                X_val[venue_index] = 1

        X_val = pd.DataFrame(X_val.reshape(1,-1),columns=X_test.columns)
        fill_method(X_val)
        cls = GradientBoostingClassifier(n_estimators=int(X_train.shape[1]/2),random_state=0)
        cls.fit(X_train,y_train)
        pred = cls.predict_proba(X_test)[:,1]
        pred = pred > 0.5
        from sklearn.metrics import confusion_matrix,classification_report
        print(player + ' :')
        print(confusion_matrix(y_test,pred))
        print(cls.score(X_test,y_test))
        print('Val per'+str(cls.predict_proba(X_val)[:,1]))

In [136]:
for i in KXIP :
    batting_per(batting_score,i,'KXIP','KKR','Punjab Cricket Association Stadium Mohali',teams,venues)

MA Agarwal :
[[4 1]
 [0 0]]
0.8
Val per[0.79165821]
R Ashwin :
[[3 1]
 [1 0]]
0.6
Val per[0.01028303]
CH Gayle :
[[5]]
1.0
Val per[0.56233282]
MC Henriques :
[[5]]
1.0
Val per[0.21476224]
Mandeep Singh :
[[2 2]
 [0 1]]
0.6
Val per[0.16713628]
DA Miller :
[[1 1]
 [2 1]]
0.4
Val per[0.10931182]
KK Nair :
[[3 0]
 [1 1]]
0.8
Val per[0.65219179]
KL Rahul :
[[0 1]
 [0 4]]
0.8
Val per[0.75443552]


In [140]:
for i in KKR :
    batting_per(batting_score,i,'KKR','KXIP','Punjab Cricket Association Stadium Mohali',teams,venues)

KD Karthik :
[[1 1]
 [2 1]]
0.4
Val per[0.63370311]
PP Chawla :
[[5]]
1.0
Val per[0.00692415]
CA Lynn :
[[1 2]
 [2 0]]
0.2
Val per[0.81153833]
SP Narine :
[[1 0]
 [4 0]]
0.2
Val per[0.10932101]
N Rana :
[[3 1]
 [1 0]]
0.6
Val per[0.32966388]
AD Russell :
[[2 2]
 [1 0]]
0.4
Val per[0.39576018]
RV Uthappa :
[[4 0]
 [1 0]]
0.8
Val per[0.54315458]


In [76]:
def batting_per(batting_score,player,own_team,opp_team,match_venue,teams,venues) :
    df = batting_score[batting_score['batsman']==player]
    df = df.sort_values(by='match_id')
    df['pre1'] = df['batsman_runs'].shift(1)
    df['pre2'] = df['batsman_runs'].shift(2)
    df['pre3'] = df['batsman_runs'].shift(3)
    df.dropna(inplace=True)
    opp_df = pd.DataFrame()
    for i in [i for i in teams if i not in own] :
        opp = batting_score[(batting_score['batsman']==player) & (batting_score['Opp_Team']==i)]
        opp = opp.sort_values(by='match_id')
        opp['pre_opp1'] = opp['batsman_runs'].shift(1)
        opp['pre_opp2'] = opp['batsman_runs'].shift(2)
        opp['pre_opp3'] = opp['batsman_runs'].shift(3)
        opp_df = opp_df.append(opp)
    opp_df = opp_df[['match_id','batsman','Opp_Team','venue','pre_opp1','pre_opp2','pre_opp3']]
    bat1 = pd.merge(df,opp_df,left_on=['match_id','batsman','Opp_Team','venue'],right_on=['match_id','batsman','Opp_Team','venue'],how='left')
    venue_df = pd.DataFrame()
    for j in venues :
        ven = batting_score[(batting_score['batsman']==player) & (batting_score['venue']==j)]
        ven = ven.sort_values(by='match_id')
        ven['pre_venue1'] = ven['batsman_runs'].shift(1)
        ven['pre_venue2'] = ven['batsman_runs'].shift(2)
        ven['pre_venue3'] = ven['batsman_runs'].shift(3)
        venue_df = venue_df.append(ven)
    venue_df = venue_df[['match_id','batsman','Opp_Team','venue','pre_venue1','pre_venue2','pre_venue3']]
    bat2 = pd.merge(bat1,venue_df,left_on=['match_id','batsman','Opp_Team','venue'],right_on=['match_id','batsman','Opp_Team','venue'],how='left')
    bowl_opp_df = pd.DataFrame()
    for i in [i for i in teams if i not in own] :
        bowl_opp = batting_score[(batting_score['Own_Team']==own) & (batting_score['Opp_Team']==i)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
        bowl_opp = bowl_opp.sort_values(by='match_id')
        bowl_opp['avg'] = bowl_opp['batsman_runs'] / bowl_opp['out_bowler'].apply(lambda x: 1 if x==0 else x)
        bowl_opp['bowl_opp1'] = bowl_opp['avg'].shift(1)
        bowl_opp['bowl_opp2'] = bowl_opp['avg'].shift(2)
        bowl_opp['bowl_opp3'] = bowl_opp['avg'].shift(3)
        bowl_opp_df = bowl_opp_df.append(bowl_opp)
    bat3 = pd.merge(bat2,bowl_opp_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
    bat3 = bat3[['match_id', 'batsman', 'Own_Team', 'Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 'pre1', 'pre2', 'pre3', 'pre_opp1',
           'pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 'pre_venue3','bowl_opp1', 'bowl_opp2','bowl_opp3']]
    bowl_df = pd.DataFrame()
    for i in [i for i in teams if i not in own] :
        bowl = batting_score[(batting_score['Opp_Team']==i)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
        bowl = bowl.sort_values(by='match_id')
        bowl['avg'] = bowl['batsman_runs'] / bowl['out_bowler'].apply(lambda x: 1 if x==0 else x)
        bowl['bowl_pre1'] = bowl['avg'].shift(1)
        bowl['bowl_pre2'] = bowl['avg'].shift(2)
        bowl['bowl_pre3'] = bowl['avg'].shift(3)
        bowl_df = bowl_df.append(bowl)
        bowl_df.dropna(inplace=True)
    bat4 = pd.merge(bat3,bowl_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
    bat4 = bat4[['match_id', 'batsman', 'Own_Team', 'Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 'pre1', 'pre2', 'pre3', 'pre_opp1',
           'pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 'pre_venue3','bowl_pre1', 'bowl_pre2', 'bowl_pre3','bowl_opp1', 'bowl_opp2','bowl_opp3']]
    bowl_venue_df = pd.DataFrame()
    for i in [i for i in teams if i not in own] :
        for j in venues :
            bowl_venue = batting_score[(batting_score['Opp_Team']==i) & (batting_score['venue']==j)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
            bowl_venue = bowl_venue.sort_values(by='match_id')
            bowl_venue['avg'] = bowl_venue['batsman_runs'] / bowl_venue['out_bowler'].apply(lambda x: 1 if x==0 else x)
            bowl_venue['venue_opp1'] = bowl_venue['avg'].shift(1)
            bowl_venue['venue_opp2'] = bowl_venue['avg'].shift(2)
            bowl_venue['venue_opp3'] = bowl_venue['avg'].shift(3)
            bowl_venue_df = bowl_venue_df.append(bowl_venue)
    bat5 = pd.merge(bat4,bowl_venue_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
    bat5 = bat5[['Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 
                 'pre1', 'pre2', 'pre3', 'pre_opp1','pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 
                 'pre_venue3','bowl_pre1', 'bowl_pre2', 'bowl_pre3','bowl_opp1', 'bowl_opp2','bowl_opp3',
                 'venue_opp1','venue_opp2', 'venue_opp3']]
    bat5['pre_opp1'].fillna(value=bat5[['pre1','pre2','pre3']].apply(fillna,axis=1),inplace=True)
    bat5['pre_opp2'].fillna(value=bat5['pre_opp1'],inplace=True)
    bat5['pre_opp3'].fillna(value=bat5[['pre_opp1','pre_opp2']].apply(fillna2,axis=1),inplace=True)

    bat5['pre_venue1'].fillna(value=bat5[['pre1','pre2','pre3']].apply(fillna,axis=1),inplace=True)
    bat5['pre_venue2'].fillna(value=bat5['pre_venue1'],inplace=True)
    bat5['pre_venue3'].fillna(value=bat5[['pre_venue1','pre_venue2']].apply(fillna2,axis=1),inplace=True)

    bat5['bowl_opp1'].fillna(value=bat5[['bowl_pre1','bowl_pre2','bowl_pre3']].apply(fillna,axis=1),inplace=True)
    bat5['bowl_opp2'].fillna(value=bat5['bowl_opp1'],inplace=True)
    bat5['bowl_opp3'].fillna(value=bat5[['bowl_opp1','bowl_opp2']].apply(fillna2,axis=1),inplace=True)

    bat5['venue_opp1'].fillna(value=bat5[['bowl_pre1','bowl_pre2','bowl_pre3']].apply(fillna,axis=1),inplace=True)
    bat5['venue_opp2'].fillna(value=bat5['venue_opp1'],inplace=True)
    bat5['venue_opp3'].fillna(value=bat5[['venue_opp1','venue_opp2']].apply(fillna2,axis=1),inplace=True)

    bat_dummies = pd.get_dummies(bat5,columns=['Opp_Team','venue'])
    bat_dummies.dropna(inplace=True)
    if bat_dummies.shape[0] >= 25 :
        bat_dummies['is_played']=bat_dummies[['batsman_runs_x','out_bowler_x']].apply(is_played,axis=1)
        X_train = bat_dummies.iloc[:-5,2:-1]
        y_train = bat_dummies.iloc[:-5,-1]
        X_test = bat_dummies.iloc[-5:,2:-1]
        print(X_test.columns)
        y_test = bat_dummies.iloc[-5:,-1]
        X_val = np.zeros(X_test.shape[1])
        X_val[0:3] = batting_score[(batting_score['batsman']=='KL Rahul')].sort_values(by='match_id').tail(3)['batsman_runs'].values
        X_val[3:6] = batting_score[(batting_score['batsman']=='KL Rahul') & 
                                   (batting_score['Opp_Team']=='KKR')].sort_values(by='match_id').tail(3)['batsman_runs'].values
        X_val[6:9] = batting_score[(batting_score['batsman']=='KL Rahul') & 
                                   (batting_score['venue']=='Punjab Cricket Association Stadium Mohali')].sort_values(by='match_id').tail(3)['batsman_runs'].values
        b1 = batting_score[(batting_score['Opp_Team']=='KKR')].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']].sort_values(by='match_id').tail(3)[['batsman_runs','out_bowler']]
        b1['avg'] = b1['batsman_runs'] / b1['out_bowler'].apply(lambda x: 1 if x==0 else x)
        X_val[9:12] = b1['avg'].values
        b2 = batting_score[(batting_score['venue']=='Punjab Cricket Association Stadium Mohali') & (batting_score['Opp_Team']=='KKR')].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']].sort_values(by='match_id').tail(3)[['batsman_runs','out_bowler']]
        b2['avg'] = b2['batsman_runs'] / b2['out_bowler'].apply(lambda x: 1 if x==0 else x)
        X_val[12:15] = b2['avg'].values
        b3 = batting_score[(batting_score['Own_Team']=='KXIP') & (batting_score['venue']=='Punjab Cricket Association Stadium Mohali')].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']].sort_values(by='match_id').tail(3)[['batsman_runs','out_bowler']]
        b3['avg'] = b3['batsman_runs'] / b3['out_bowler'].apply(lambda x: 1 if x==0 else x)
        X_val[15:18] = b3['avg'].values
        opposition = 'Opp_Team_'+ 'KKR'
        for i in range(0,len(X_train.columns)) :
            if opposition in X_train.columns[i] :
                opp_index = i
        X_val[opp_index] = 1
        match_venue = 'venue_'+ 'Punjab Cricket Association Stadium Mohali'
        for i in range(0,len(X_train.columns)) :
            if match_venue in X_train.columns[i] :
                venue_index = i
        X_val[venue_index] = 1        
        cls = GradientBoostingClassifier(n_estimators=int(X_train.shape[1]/2),random_state=0)
        cls.fit(X_train,y_train)
        pred = cls.predict_proba(X_test)[:,1]
        pred = pred > 0.5
        from sklearn.metrics import confusion_matrix,classification_report
        print(player + ' :')
        print(confusion_matrix(y_test,pred))
        print(cls.score(X_test,y_test))

In [93]:
X_val

array([22.        , 99.        ,  8.        ,  0.        , 44.        ,
       39.        , 40.        , 37.        , 17.        , 34.33333333,
       21.25      , 27.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

pre1  pre2  pre3  pre_opp1  pre_opp2  pre_opp3  pre_venue1  pre_venue2  \
0  22.0  99.0   8.0       0.0      44.0      39.0        40.0        37.0   

   pre_venue3  bowl_pre1           ...            venue_Feroz Shah Kotla  \
0        17.0  34.333333           ...                               0.0   

   venue_Holkar Cricket Stadium  venue_JSCA International Stadium Complex  \
0                           0.0                                       0.0   

   venue_M Chinnaswamy Stadium  venue_MA Chidambaram Stadium Chepauk  \
0                          0.0                                   0.0   

   venue_Maharashtra Cricket Association Stadium  \
0                                            0.0   

   venue_Punjab Cricket Association Stadium Mohali  \
0                                              1.0   

   venue_Rajiv Gandhi International Stadium Uppal  \
0                                             0.0   

   venue_Sawai Mansingh Stadium  venue_Wankhede Stadium  
0                           0.0                     0.0  

[1 rows x 38 columns]

In [99]:
X_val

array([22.        , 99.        ,  8.        ,  0.        , 44.        ,
       39.        , 40.        , 37.        , 17.        , 34.33333333,
       21.25      , 27.        , 12.        ,  8.5       , 20.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

In [77]:
for i in KXIP :
    batting_per(batting_score,i,'KXIP',teams,venues)

Index(['pre1', 'pre2', 'pre3', 'pre_opp1', 'pre_opp2', 'pre_opp3',
       'pre_venue1', 'pre_venue2', 'pre_venue3', 'bowl_pre1', 'bowl_pre2',
       'bowl_pre3', 'bowl_opp1', 'bowl_opp2', 'bowl_opp3', 'venue_opp1',
       'venue_opp2', 'venue_opp3', 'Opp_Team_CSK', 'Opp_Team_DC',
       'Opp_Team_KKR', 'Opp_Team_MI', 'Opp_Team_RCB', 'Opp_Team_RR',
       'Opp_Team_SRH', 'venue_Brabourne Stadium',
       'venue_Dr YS Rajasekhara Reddy ACAVDCA Cricket Stadium',
       'venue_Eden Gardens', 'venue_Feroz Shah Kotla',
       'venue_Holkar Cricket Stadium', 'venue_M Chinnaswamy Stadium',
       'venue_MA Chidambaram Stadium Chepauk',
       'venue_Maharashtra Cricket Association Stadium', 'venue_Nehru Stadium',
       'venue_Punjab Cricket Association Stadium Mohali',
       'venue_Rajiv Gandhi International Stadium Uppal',
       'venue_Sardar Patel Stadium Motera', 'venue_Wankhede Stadium'],
      dtype='object')
MA Agarwal :
[[4 1]
 [0 0]]
0.8
Index(['pre1', 'pre2', 'pre3', 'pre_opp1', 'p

In [36]:
for i in KKR :
    batting_per(batting_score,i,'KKR')

KD Karthik :
[[1 1]
 [2 1]]
0.4
PP Chawla :
[[5]]
1.0
CA Lynn :
[[1 2]
 [2 0]]
0.2
SP Narine :
[[1 0]
 [4 0]]
0.2
N Rana :
[[3 1]
 [1 0]]
0.6
AD Russell :
[[2 2]
 [1 0]]
0.4
RV Uthappa :
[[4 0]
 [1 0]]
0.8


In [56]:
df = batting_score[batting_score['batsman']=='R Ashwin']
df = df.sort_values(by='match_id')
df['pre1'] = df['batsman_runs'].shift(1)
df['pre2'] = df['batsman_runs'].shift(2)
df['pre3'] = df['batsman_runs'].shift(3)
df.dropna(inplace=True)

In [57]:
opp_df = pd.DataFrame()
for i in ['CSK','RCB','KKR','SRH','MI','DC','RR'] :
    opp = batting_score[(batting_score['batsman']=='R Ashwin') & (batting_score['Opp_Team']==i)]
    opp = opp.sort_values(by='match_id')
    opp['pre_opp1'] = opp['batsman_runs'].shift(1)
    opp['pre_opp2'] = opp['batsman_runs'].shift(2)
    opp['pre_opp3'] = opp['batsman_runs'].shift(3)
    opp_df = opp_df.append(opp)
opp_df = opp_df[['match_id','batsman','Opp_Team','venue','pre_opp1','pre_opp2','pre_opp3']]
bat1 = pd.merge(df,opp_df,left_on=['match_id','batsman','Opp_Team','venue'],right_on=['match_id','batsman','Opp_Team','venue'],how='left')

In [58]:
venue_df = pd.DataFrame()
for j in venues :
    ven = batting_score[(batting_score['batsman']=='R Ashwin') & (batting_score['venue']==j)]
    ven = ven.sort_values(by='match_id')
    ven['pre_venue1'] = ven['batsman_runs'].shift(1)
    ven['pre_venue2'] = ven['batsman_runs'].shift(2)
    ven['pre_venue3'] = ven['batsman_runs'].shift(3)
    venue_df = venue_df.append(ven)
venue_df = venue_df[['match_id','batsman','Opp_Team','venue','pre_venue1','pre_venue2','pre_venue3']]
bat2 = pd.merge(bat1,venue_df,left_on=['match_id','batsman','Opp_Team','venue'],right_on=['match_id','batsman','Opp_Team','venue'],how='left')

In [59]:
bowl_opp_df = pd.DataFrame()
for i in ['CSK','RCB','KKR','SRH','MI','DC','RR'] :
    bowl_opp = batting_score[(batting_score['Own_Team']=='KXIP') & (batting_score['Opp_Team']==i)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
    bowl_opp = bowl_opp.sort_values(by='match_id')
    bowl_opp['avg'] = bowl_opp['batsman_runs'] / bowl_opp['out_bowler'].apply(lambda x: 1 if x==0 else x)
    bowl_opp['bowl_opp1'] = bowl_opp['avg'].shift(1)
    bowl_opp['bowl_opp2'] = bowl_opp['avg'].shift(2)
    bowl_opp['bowl_opp3'] = bowl_opp['avg'].shift(3)
    bowl_opp_df = bowl_opp_df.append(bowl_opp)
bat3 = pd.merge(bat2,bowl_opp_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
bat3 = bat3[['match_id', 'batsman', 'Own_Team', 'Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 'pre1', 'pre2', 'pre3', 'pre_opp1',
       'pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 'pre_venue3','bowl_opp1', 'bowl_opp2','bowl_opp3']]

In [60]:
bowl_df = pd.DataFrame()
for i in ['CSK','RCB','KKR','SRH','MI','DC','RR'] :
    bowl = batting_score[(batting_score['Opp_Team']==i)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
    bowl = bowl.sort_values(by='match_id')
    bowl['avg'] = bowl['batsman_runs'] / bowl['out_bowler'].apply(lambda x: 1 if x==0 else x)
    bowl['bowl_pre1'] = bowl['avg'].shift(1)
    bowl['bowl_pre2'] = bowl['avg'].shift(2)
    bowl['bowl_pre3'] = bowl['avg'].shift(3)
    bowl_df = bowl_df.append(bowl)
    bowl_df.dropna(inplace=True)
bat4 = pd.merge(bat3,bowl_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
bat4 = bat4[['match_id', 'batsman', 'Own_Team', 'Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 'pre1', 'pre2', 'pre3', 'pre_opp1',
       'pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 'pre_venue3','bowl_pre1', 'bowl_pre2', 'bowl_pre3','bowl_opp1', 'bowl_opp2','bowl_opp3']]

In [61]:
bowl_venue_df = pd.DataFrame()
for i in ['CSK','RCB','KKR','SRH','MI','DC','RR'] :
    for j in venues :
        bowl_venue = batting_score[(batting_score['Opp_Team']==i) & (batting_score['venue']==j)].groupby(by=['match_id','Opp_Team','venue'],as_index=False).sum()[['match_id','Opp_Team','venue','batsman_runs','out_bowler']]
        bowl_venue = bowl_venue.sort_values(by='match_id')
        bowl_venue['avg'] = bowl_venue['batsman_runs'] / bowl_venue['out_bowler'].apply(lambda x: 1 if x==0 else x)
        bowl_venue['venue_opp1'] = bowl_venue['avg'].shift(1)
        bowl_venue['venue_opp2'] = bowl_venue['avg'].shift(2)
        bowl_venue['venue_opp3'] = bowl_venue['avg'].shift(3)
        bowl_venue_df = bowl_venue_df.append(bowl_venue)
bat5 = pd.merge(bat4,bowl_venue_df,left_on=['match_id','Opp_Team','venue'],right_on=['match_id','Opp_Team','venue'],how='left')
bat5 = bat5[['Opp_Team', 'venue','batsman_runs_x', 'out_bowler_x', 
             'pre1', 'pre2', 'pre3', 'pre_opp1','pre_opp2', 'pre_opp3', 'pre_venue1', 'pre_venue2', 
             'pre_venue3','bowl_pre1', 'bowl_pre2', 'bowl_pre3','bowl_opp1', 'bowl_opp2','bowl_opp3',
             'venue_opp1','venue_opp2', 'venue_opp3']]

In [62]:
bat5['pre_opp1'].fillna(value=bat5[['pre1','pre2','pre3']].apply(fillna,axis=1),inplace=True)
bat5['pre_opp2'].fillna(value=bat5['pre_opp1'],inplace=True)
bat5['pre_opp3'].fillna(value=bat5[['pre_opp1','pre_opp2']].apply(fillna2,axis=1),inplace=True)

bat5['pre_venue1'].fillna(value=bat5[['pre1','pre2','pre3']].apply(fillna,axis=1),inplace=True)
bat5['pre_venue2'].fillna(value=bat5['pre_venue1'],inplace=True)
bat5['pre_venue3'].fillna(value=bat5[['pre_venue1','pre_venue2']].apply(fillna2,axis=1),inplace=True)

bat5['bowl_opp1'].fillna(value=bat5[['bowl_pre1','bowl_pre2','bowl_pre3']].apply(fillna,axis=1),inplace=True)
bat5['bowl_opp2'].fillna(value=bat5['bowl_opp1'],inplace=True)
bat5['bowl_opp3'].fillna(value=bat5[['bowl_opp1','bowl_opp2']].apply(fillna2,axis=1),inplace=True)

bat5['venue_opp1'].fillna(value=bat5[['bowl_pre1','bowl_pre2','bowl_pre3']].apply(fillna,axis=1),inplace=True)
bat5['venue_opp2'].fillna(value=bat5['venue_opp1'],inplace=True)
bat5['venue_opp3'].fillna(value=bat5[['venue_opp1','venue_opp2']].apply(fillna2,axis=1),inplace=True)

bat_dummies = pd.get_dummies(bat5,columns=['Opp_Team','venue'])
bat_dummies['is_played']=bat_dummies[['batsman_runs_x','out_bowler_x']].apply(is_played,axis=1)

In [31]:
bat_dummies.tail()

batsman_runs_x  out_bowler_x  pre1  pre2  pre3  pre_opp1  pre_opp2  \
29               1             1  14.0  27.0   1.0       1.0       1.0   
30               4             1   1.0  14.0  27.0       0.0       3.0   
31               0             1   4.0   1.0  14.0       0.0       0.0   
32              36             0   0.0   4.0   1.0       0.0       1.0   
33               1             1  36.0   0.0   4.0      14.0       1.0   

    pre_opp3  pre_venue1  pre_venue2    ...      venue_Holkar Cricket Stadium  \
29       3.0    3.000000    3.000000    ...                                 0   
30       1.5   14.000000   14.000000    ...                                 0   
31       0.0    6.333333    6.333333    ...                                 0   
32       0.0    1.666667    1.666667    ...                                 1   
33       1.0    0.000000    0.000000    ...                                 0   

    venue_JSCA International Stadium Complex  venue_M Chinnaswamy Stadium  \
29                                         0                            0   
30                                         0                            0   
31                                         0                            0   
32                                         0                            0   
33                                         0                            0   

    venue_MA Chidambaram Stadium Chepauk  \
29                                     0   
30                                     0   
31                                     0   
32                                     0   
33                                     0   

    venue_Maharashtra Cricket Association Stadium  \
29                                              0   
30                                              0   
31                                              0   
32                                              0   
33                                              1   

    venue_Punjab Cricket Association Stadium Mohali  \
29                                                0   
30                                                0   
31                                                0   
32                                                0   
33                                                0   

    venue_Rajiv Gandhi International Stadium Uppal  \
29                                               0   
30                                               1   
31                                               0   
32                                               0   
33                                               0   

    venue_Sawai Mansingh Stadium  venue_Wankhede Stadium  is_played  
29                             0                       0          0  
30                             0                       0          0  
31                             1                       0          0  
32                             0                       0          1  
33                             0                       0          0  

[5 rows x 41 columns]

In [79]:
X_train = bat_dummies.iloc[:-5,2:-1]
y_train = bat_dummies.iloc[:-5,-1]
X_test = bat_dummies.iloc[-5:,2:-1]
y_test = bat_dummies.iloc[-5:,-1]
cls = GradientBoostingClassifier(n_estimators=int(X_train.shape[1]/2),random_state=0)
cls.fit(X_train,y_train)
pred = cls.predict_proba(X_test)[:,1]
pred = pred > 0.5
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[3 1]
 [1 0]]
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       0.00      0.00      0.00         1

   micro avg       0.60      0.60      0.60         5
   macro avg       0.38      0.38      0.38         5
weighted avg       0.60      0.60      0.60         5

